<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-8PVTIFHE" failures="1" tests="6" name="UI Automation Test" time="22.434" errors="0" timestamp="2025-05-21T22:33:01 CEST">
  <testcase classname="com.ui.test.LoginTest" name="loginTestCopy1" time="2.767">
    <skipped/>
  </testcase> <!-- loginTestCopy1 -->
  <testcase classname="com.ui.test.LoginTest" name="loginTest" time="3.084"/>
  <testcase classname="com.ui.test.LoginTest" name="loginTestCopy" time="3.198"/>
  <testcase classname="com.ui.test.LoginTest" name="loginTestCopy1" time="1.644">
    <skipped/>
  </testcase> <!-- loginTestCopy1 -->
  <testcase classname="com.ui.test.LoginTest" name="loginTestCopy1" time="1.866">
    <skipped/>
  </testcase> <!-- loginTestCopy1 -->
  <testcase classname="com.ui.test.LoginTest" name="loginTestCopy1" time="2.282">
    <failure type="java.lang.AssertionError" message="expected [Kunal] but found [Kunal B]">
      <![CDATA[java.lang.AssertionError: expected [Kunal] but found [Kunal B]
at com.ui.test.LoginTest.loginTestCopy1(LoginTest.java:36)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginTestCopy1 -->
</testsuite> <!-- UI Automation Test -->
